FROM docker:dind



# start the mysql test data base and the maven container
# ENTRYPOINT docker run -d --name mysqlContainer fcastelain/mysql
# ENTRYPOINT docker run -d --name mavenContainer fcastelain/maven

# delete and recreate the bridge
# ENTRYPOINT docker network rm testNetwork
# ENTRYPOINT docker network create testNetwork

# add the both containers to the network
# ENTRYPOINT docker network connect testNetwork mysqlContainer
# ENTRYPOINT docker network connect testNetwork mavenContainer


